# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIAccessRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_time', models.DateTimeField(auto_created=True)),
                ('response_time', models.IntegerField()),
                ('endpoint', models.CharField(max_length=32)),
            ],
        ),
    ]
