# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shinobu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stickynote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=512)),
                ('styletext', models.CharField(max_length=1024)),
                ('position_x', models.IntegerField()),
                ('position_y', models.IntegerField()),
                ('position_z', models.IntegerField()),
            ],
        ),
    ]
