# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 01:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shinobu', '0002_stickynote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stickynote',
            old_name='styletext',
            new_name='style',
        ),
        migrations.RenameField(
            model_name='stickynote',
            old_name='position_x',
            new_name='x',
        ),
        migrations.RenameField(
            model_name='stickynote',
            old_name='position_y',
            new_name='y',
        ),
        migrations.RenameField(
            model_name='stickynote',
            old_name='position_z',
            new_name='z',
        ),
    ]
