# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shinobu', '0004_delete_procedure'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSpam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2000)),
            ],
        ),
    ]
