# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 22:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shinobu', '0006_discussiontopic_trashtakeout'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='HouseMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='trashtakeout',
            name='who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shinobu.HouseMember'),
        ),
        migrations.AddField(
            model_name='house',
            name='members',
            field=models.ManyToManyField(to='shinobu.HouseMember'),
        ),
    ]
