# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 22:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shinobu', '0007_auto_20170313_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='trashtakeout',
            name='house',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shinobu.House'),
            preserve_default=False,
        ),
    ]
