# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('isogen', '0003_auto_20170105_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_posted', models.DateTimeField()),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=140)),
                ('body', models.TextField()),
                ('header_picture', models.ImageField(blank=True, upload_to='')),
                ('author', models.ManyToManyField(to='isogen.IsogenMember')),
                ('post_tags', models.ManyToManyField(blank=True, to='isogen.Tag')),
            ],
        ),
    ]
