# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='subtitle',
            field=models.CharField(default='donger', max_length=400),
            preserve_default=False,
        ),
    ]
