# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpost_related_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='url',
            field=models.CharField(default=None, editable=False, max_length=64, null=True, unique=True),
        ),
    ]
