# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isogen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
