# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isogen', '0002_auto_20161227_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='/static/downloads'),
        ),
    ]
