# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 22:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isogen', '0002_auto_20161230_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='members_allowed',
            field=models.ManyToManyField(blank=True, default=None, to=settings.AUTH_USER_MODEL),
        ),
    ]
