# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isogen', '0003_auto_20161228_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectoryEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=400)),
                ('picture', models.ImageField(upload_to='')),
                ('logo', models.ImageField(upload_to='')),
                ('priority', models.SmallIntegerField()),
                ('tags', models.ManyToManyField(to='isogen.Tag')),
            ],
        ),
        migrations.DeleteModel(
            name='Subdomain',
        ),
    ]
