# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isogen', '0003_auto_20161227_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='account_required',
        ),
        migrations.AddField(
            model_name='file',
            name='members_allowed',
            field=models.ManyToManyField(blank=True, default=None, to='isogen.Member'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='downloads'),
        ),
        migrations.AlterField(
            model_name='file',
            name='tags',
            field=models.ManyToManyField(blank=True, default=None, to='isogen.Tag'),
        ),
    ]
