# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isogen', '0004_auto_20170403_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='url',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
