# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isogen', '0004_auto_20161229_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directoryentry',
            name='url',
            field=models.CharField(max_length=100),
        ),
    ]
