# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isogen', '0007_auto_20161229_0046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directoryentry',
            name='picture',
        ),
        migrations.AddField(
            model_name='directoryentry',
            name='icon',
            field=models.CharField(default='fa-cloud-download', max_length=32),
            preserve_default=False,
        ),
    ]
