# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isogen', '0009_auto_20161229_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='description',
            field=models.CharField(default='No description provided.', max_length=400),
        ),
    ]
